// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCKQRyIEdAfeQ5nQur5X6CFZ14CnPpKI',
    appId: '1:626249191554:web:b850e5c3191fdec29ca49b',
    messagingSenderId: '626249191554',
    projectId: 'sugar-plus-340e2',
    authDomain: 'sugar-plus-340e2.firebaseapp.com',
    storageBucket: 'sugar-plus-340e2.firebasestorage.app',
    measurementId: 'G-4EDKL17351',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcQS1yJ0uY-d16xk7R57kqlgIJDsvjw7g',
    appId: '1:626249191554:android:4abc8991542b8e5b9ca49b',
    messagingSenderId: '626249191554',
    projectId: 'sugar-plus-340e2',
    storageBucket: 'sugar-plus-340e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-csYwOwZo_NVrl7cCeA7L_9-GFChHqI',
    appId: '1:626249191554:ios:5f739812ba21694b9ca49b',
    messagingSenderId: '626249191554',
    projectId: 'sugar-plus-340e2',
    storageBucket: 'sugar-plus-340e2.firebasestorage.app',
    iosClientId: '626249191554-1e0n84pa787iougkf0mge4i2i66tu7jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetesTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-csYwOwZo_NVrl7cCeA7L_9-GFChHqI',
    appId: '1:626249191554:ios:5f739812ba21694b9ca49b',
    messagingSenderId: '626249191554',
    projectId: 'sugar-plus-340e2',
    storageBucket: 'sugar-plus-340e2.firebasestorage.app',
    iosClientId: '626249191554-1e0n84pa787iougkf0mge4i2i66tu7jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetesTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCKQRyIEdAfeQ5nQur5X6CFZ14CnPpKI',
    appId: '1:626249191554:web:0d81eacd0baf359e9ca49b',
    messagingSenderId: '626249191554',
    projectId: 'sugar-plus-340e2',
    authDomain: 'sugar-plus-340e2.firebaseapp.com',
    storageBucket: 'sugar-plus-340e2.firebasestorage.app',
    measurementId: 'G-T2BNR8ZWJV',
  );
}
